include:
  # - path: dockge/docker-compose.dockge.yml
  #   env_file:
  #     - .env

  # - path: prometheus/docker-compose.prometheus.yml
  #   env_file:
  #     - .env

  # - path: cadvisor/docker-compose.cadvisor.yml
  #   env_file:
  #     - .env

  # - path: node-exporter/docker-compose.node-exporter.yml
  #   env_file:
  #     - .env

  # - path: forgejo/docker-compose.forgejo.yml
  #   env_file:
  #     - .env
  #     - forgejo/.env
  
  # - path: glance/docker-compose.glance.yml
  #   env_file:
  #     - .env
  #     - glance/.env
  
  - path: caddy/docker-compose.caddy.yml
    env_file:
      - .env

  - path: m3v-api/docker-compose.m3v-api.yml
    env_file:
      - .env
      - m3v-api/.env

  - path: watchtower/docker-compose.watchtower.yml
    env_file:
      - .env
      - watchtower/.env

  - path: feishin/docker-compose.feishin.yml
    env_file:
      - .env
      - feishin/.env

  - path: ntfy/docker-compose.ntfy.yml
    env_file:
      - .env
      - ntfy/.env

  - path: uptime-kuma/docker-compose.uptime-kuma.yml
    env_file:
      - .env

  - path: vaultwarden/docker-compose.vaultwarden.yml
    env_file:
      - .env

  - path: silverbullet/docker-compose.silverbullet.yml
    env_file:
      - .env
      - silverbullet/.env

networks:
  net:
    driver: bridge
    attachable: true