services:
  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    container_name: feishin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9180"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      SERVER_NAME: "m3v's music box"
      SERVER_LOCK: "true"
      SERVER_TYPE: navidrome
      SERVER_URL: https://navidrome.m3v.dev
      LEGACY_AUTHENTICATION: "false"
      ANALYTICS_DISABLED: "true"
      FS_GENERAL_ACCENT: rgb(53,116,252)
      FS_GENERAL_ALBUM_BACKGROUND: "false"
      FS_GENERAL_ALBUM_BACKGROUND_BLUR: "3"
      FS_GENERAL_ARTIST_BACKGROUND: "true"
      FS_GENERAL_ARTIST_BACKGROUND_BLUR: "3"
      FS_GENERAL_BLUR_EXPLICIT_IMAGES: "false"
      FS_GENERAL_COMBINED_LYRICS_AND_VISUALIZER: "false"
      FS_GENERAL_ENABLE_GRID_MULTI_SELECT: "false"
      FS_GENERAL_EXTERNAL_LINKS: "true"
      FS_GENERAL_FOLLOW_CURRENT_SONG: "true"
      FS_GENERAL_FOLLOW_SYSTEM_THEME: "false"
      FS_GENERAL_HOME_FEATURE: "true"
      FS_GENERAL_HOME_FEATURE_STYLE: single
      FS_GENERAL_LANGUAGE: en
      FS_GENERAL_THEME: defaultDark
      FS_GENERAL_THEME_DARK: defaultDark
      FS_GENERAL_THEME_LIGHT: defaultLight
      FS_GENERAL_LASTFM_API_KEY: ${LASTFM_APIKEY}
      FS_GENERAL_LAST_FM: "true"
      FS_GENERAL_LISTEN_BRAINZ: "true"
      FS_GENERAL_MUSIC_BRAINZ: "true"
      FS_GENERAL_NATIVE_ASPECT_RATIO: "false"
      FS_GENERAL_PLAYERBAR_OPEN_DRAWER: "false"
      FS_GENERAL_PRIMARY_SHADE: "6"
      FS_GENERAL_QOBUZ: "true"
      FS_GENERAL_RESUME: "true"
      FS_GENERAL_SHOW_LYRICS_IN_SIDEBAR: "true"
      FS_GENERAL_SHOW_RATINGS: "true"
      FS_GENERAL_SHOW_VISUALIZER_IN_SIDEBAR: "true"
      FS_GENERAL_SIDEBAR_COLLAPSED_NAVIGATION: "true"
      FS_GENERAL_SIDEBAR_COLLAPSE_SHARED: "false"
      FS_GENERAL_SIDEBAR_PLAYLIST_FOLDERS: "true"
      FS_GENERAL_SIDEBAR_PLAYLIST_FOLDER_SEPARATOR: /
      FS_GENERAL_SIDEBAR_PLAYLIST_FOLDER_TREE_INDENT: "16"
      FS_GENERAL_SIDEBAR_PLAYLIST_FOLDER_VIEW: tree
      FS_GENERAL_SIDEBAR_PLAYLIST_LIST: "true"
      FS_GENERAL_SIDEBAR_PLAYLIST_MODE: expanded
      FS_GENERAL_SIDEBAR_PLAYLIST_SORTING: "false"
      FS_GENERAL_SIDE_QUEUE_TYPE: sideQueue
      FS_GENERAL_SIDE_QUEUE_LAYOUT: horizontal
      FS_GENERAL_USE_THEME_ACCENT_COLOR: "false"
      FS_GENERAL_USE_THEME_PRIMARY_SHADE: "true"
      FS_GENERAL_ZOOM_FACTOR: "100"
      FS_PLAYBACK_MEDIA_SESSION: "false"
      FS_PLAYBACK_WEB_AUDIO: "true"
      FS_PLAYBACK_AUDIO_FADE_ON_STATUS_CHANGE: "true"
      FS_PLAYBACK_PRESERVE_PITCH: "true"
      FS_PLAYBACK_SCROBBLE_ENABLED: "true"
      FS_PLAYBACK_SCROBBLE_NOTIFY: "false"
      FS_PLAYBACK_SCROBBLE_AT_DURATION: "240"
      FS_PLAYBACK_SCROBBLE_AT_PERCENTAGE: "75"
      FS_PLAYBACK_TRANSCODE_ENABLED: "false"
      FS_DISCORD_ENABLED: "true"
      FS_DISCORD_CLIENT_ID: ${FS_DISCORD_CLIENT_ID}
      FS_DISCORD_DISPLAY_TYPE: song
      FS_DISCORD_LINK_TYPE: none
      FS_DISCORD_SHOW_AS_LISTENING: "true"
      FS_DISCORD_SHOW_PAUSED: "true"
      FS_DISCORD_SHOW_SERVER_IMAGE: "false"
      FS_DISCORD_SHOW_STATE_ICON: "true"
      FS_LYRICS_FETCH: "true"
      FS_LYRICS_FOLLOW: "true"
      FS_LYRICS_DELAY_MS: "0"
      FS_LYRICS_PREFER_LOCAL: "true"
      FS_LYRICS_SHOW_MATCH: "true"
      FS_LYRICS_SHOW_PROVIDER: "true"
      FS_LYRICS_ALIGNMENT: center
      FS_AUTO_DJ_ALBUM_STRATEGY: similar
      FS_AUTO_DJ_ENABLED: "false"
      FS_AUTO_DJ_ITEM_COUNT: "5"
      FS_AUTO_DJ_MODE: songs
      FS_AUTO_DJ_SONG_STRATEGY: similar
      FS_AUTO_DJ_TIMING: "1"
      FS_CSS_ENABLED: "false"
      FS_FONT_TYPE: builtIn
      FS_FONT_BUILT_IN: Inter
    ports:
      - "9181:9180"
    networks:
      - net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"