services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    depends_on:
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      TZ: ${TZ}
    volumes:
      - ${DATA_ROOT}\recyclarr:/config
    networks:
      - net
