services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    environment:
      TZ: ${TZ}
    volumes:
      - ${DATA_ROOT}/recyclarr:/config
    networks:
      - net
