services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${DATA_ROOT}/radarr:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - "7878:7878"
    networks:
      - net