services:
  komf:
    image: sndxr/komf:latest
    container_name: komf
    restart: unless-stopped
    depends_on:
      komga:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      KOMF_KOMGA_BASE_URI: http://localhost:25600
      KOMF_KOMGA_USER: max@m3v.dev
      KOMF_KOMGA_PASSWORD: ${KOMGA_PASSWORD}
      KOMF_LOG_LEVEL: INFO
      JAVA_TOOL_OPTIONS: >-
        -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact
        -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      - ${DATA_ROOT}/komf:/config
    ports:
      - "8085:8085"
    networks:
      - net
