services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --interval 86400 --cleanup --rolling-restart --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
